// client/src/app/components/dashboard/dashboard.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { HttpClient } from '@angular/common/http';
import { AuthService } from '../../core/auth.service';
import { LoaderComponent } from '../loader/loader.component';

@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule, RouterModule, LoaderComponent],
  templateUrl: './dashboard.component.html',
  styleUrls: ['./dashboard.component.css']
})
export class DashboardComponent implements OnInit {
  products: any[] = [];
  loading = true;
  error = '';
  username = 'User';

  constructor(
    private http: HttpClient,
    private authService: AuthService
  ) { }

  ngOnInit() {
    this.authService.username$.subscribe(name => {
      this.username = name;
    });
    this.fetchMySearches();
  }

  fetchMySearches() {
    this.loading = true;
    this.http.get<any>('http://localhost:5000/api/mysearches',
      { headers: { Authorization: `Bearer ${this.authService.getToken()}` } }
    )
      .subscribe({
        next: (response) => {
          this.products = response.products || [];
          this.loading = false;
        },
        error: (err) => {
          this.error = 'Failed to load your searches. Please try again later.';
          this.loading = false;
          console.error('Error fetching searches:', err);
        }
      });
  }

  trackByProductId(index: number, product: any): string {
    return product.product_id;
  }
}
<div class="min-h-screen bg-gradient-to-br from-gray-900 via-gray-950 to-black p-6">
  <div class="max-w-7xl mx-auto">
    <!-- Welcome Section -->
    <div class="mb-10">
      <h1 class="text-4xl font-bold text-fuchsia-200 mb-2">Welcome, {{ username }}!</h1>
      <p class="text-gray-400">Your recent product searches</p>
    </div>

    <!-- Loading State -->
    <app-loader *ngIf="loading"></app-loader>

    <!-- Error State -->
    <div *ngIf="error && !loading" class="bg-red-900/30 border border-red-700 rounded-lg p-4 mb-6">
      <p class="text-red-300">{{ error }}</p>
    </div>

    <!-- Products Grid -->
    <div *ngIf="!loading && !error">
      <!-- No Results State -->
      <div *ngIf="products.length === 0" class="bg-gray-800/50 border border-gray-700 rounded-xl p-8 text-center">
        <svg xmlns="http://www.w3.org/2000/svg" class="h-12 w-12 mx-auto text-gray-500 mb-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M9.172 16.172a4 4 0 015.656 0M9 10h.01M15 10h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
        </svg>
        <h3 class="text-xl font-medium text-gray-300 mb-2">No recent searches found</h3>
        <p class="text-gray-500">Your search history will appear here</p>
      </div>

      <!-- Results Grid -->
      <div *ngIf="products.length > 0" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        <div *ngFor="let product of products; trackBy: trackByProductId" 
             class="bg-gray-800 rounded-xl overflow-hidden border border-gray-700 hover:border-fuchsia-500 transition-all duration-300 hover:shadow-lg hover:shadow-fuchsia-900/20 group">
          <a [href]="product.url" target="_blank" class="block">
            <div class="h-64 overflow-hidden flex items-center justify-center bg-gray-900 relative">
              <img [src]="product.image" [alt]="product.name" 
                   class="object-contain h-full transition-transform duration-300 group-hover:scale-105">
              <div class="absolute inset-0 bg-gradient-to-t from-black/70 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300 flex items-end p-4">
                <span class="text-white text-sm font-medium">View on Amazon</span>
              </div>
            </div>
            <div class="p-4">
              <h3 class="text-fuchsia-200 font-medium text-lg mb-2 line-clamp-2">{{ product.name }}</h3>
              <div class="flex justify-between items-center">
                <span class="text-gray-400 text-sm">Product ID: {{ product.product_id }}</span>
                <button class="text-fuchsia-400 hover:text-fuchsia-300 text-sm font-medium">
                  Analyze
                </button>
              </div>
            </div>
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

// client_react/src/Components/Dashboard.jsx
import { useState, useEffect } from 'react';
import api from '../Hooks/interceptor';
import Loader from '../Components/Loader';

const Dashboard = () => {
  const [products, setProducts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    const fetchProducts = async () => {
      try {
        const response = await api.get('/api/mysearches');
        setProducts(response.data);
      } catch (err) {
        setError('Failed to load products');
        console.error('Error fetching products:', err);
      } finally {
        setLoading(false);
      }
    };

    fetchProducts();
  }, []);

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-950 to-black p-6">
      <div className="max-w-7xl mx-auto">
        <h1 className="text-3xl font-bold text-fuchsia-200 mb-8">Dashboard</h1>
        
        <Loader isLoading={loading} />

        {error && !loading && (
          <div className="bg-red-900/30 border border-red-700 rounded-lg p-4 mb-6">
            <p className="text-red-300">{error}</p>
          </div>
        )}

        {products.length > 0 && !loading && (
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {products.map((product) => (
              <div
                key={product.id}
                className="bg-gray-800/60 border border-gray-700 rounded-xl p-6 hover:shadow-lg hover:shadow-fuchsia-900/20 transition duration-300"
              >
                <h3 className="text-xl font-bold text-fuchsia-200 mb-2">
                  {product.name}
                </h3>
                <p className="text-gray-300 mb-4">{product.summary}</p>
                <div className="flex justify-between items-center">
                  <span className="text-yellow-400 flex items-center">
                    <svg
                      className="h-5 w-5 mr-1"
                      fill="currentColor"
                      viewBox="0 0 20 20"
                    >
                      <path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.286 3.97a1 1 0 00.95.69h4.176c.969 0 1.371 1.24.588 1.81l-3.38 2.455a1 1 0 00-.364 1.118l1.287 3.97c.3.921-.755 1.688-1.54 1.118l-3.381-2.455a1 1 0 00-1.175 0l-3.381 2.455c-.785.57-1.84-.197-1.54-1.118l1.287-3.97a1 1 0 00-.364-1.118L2.049 9.397c-.783-.57-.38-1.81.588-1.81h4.176a1 1 0 00.95-.69l1.286-3.97z" />
                    </svg>
                    {product.rating}
                  </span>
                  <a
                    href={`/product/${product.id}`}
                    className="text-fuchsia-400 hover:text-fuchsia-300 text-sm font-medium"
                  >
                    View Details →
                  </a>
                </div>
              </div>
            ))}
          </div>
        )}

        {products.length === 0 && !loading && !error && (
          <div className="text-center py-12">
            <p className="text-gray-400">No products found</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default Dashboard;
