// client/src/app/auth/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule, Router } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { LoaderComponent } from '../../components/loader/loader.component';
import { HttpClient } from '@angular/common/http';
import { AuthService } from '../../core/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule, LoaderComponent],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  username: string = '';
  password: string = '';
  loading: boolean = false;

  constructor(
    private http: HttpClient,
    private router: Router,
    private authService: AuthService
  ) {}

  onLogin() {
    if (!this.username || !this.password) return;

    this.loading = true;

    this.http.post('http://localhost:5000/api/login', {
      username: this.username,
      password: this.password
    }).subscribe({
      next: (response: any) => {
        this.authService.login(response.access_token, response.username);
        this.router.navigate(['/dashboard']);
      },
      error: (err) => {
        alert('Login failed. Check your credentials.');
        this.loading = false;
      },
      complete: () => {
        this.loading = false;
      }
    });
  }
}
<div
  class="min-h-screen bg-gradient-to-br from-gray-900 via-gray-950 to-black flex items-center justify-center p-6"
>
  <div
    class="bg-gradient-to-br from-gray-900 via-gray-800 to-black rounded-3xl shadow-2xl overflow-hidden w-full max-w-xl border border-gray-800"
  >
    <!-- Decorative Header -->
    <div class="text-center py-8 px-10">
      <!-- <div class="bg-gradient-to-r from-violet-900 via bg-gray-700 to-fuchsia-800 py-8 px-10"> -->
      <h2 class="text-3xl font-bold text-white">Welcome Back</h2>
      <p class="text-indigo-200 text-lg mt-1">Sign in to your account</p>
    </div>

    <div class="border-t border-violet-700"></div>
    <!-- <p class="text-red-500 text-sm">Form Valid: {{ loginForm.valid }}</p> -->
    <!-- Form -->
    <div class="p-10">
      <form class="space-y-8" (ngSubmit)="onLogin()" #loginForm="ngForm">
        <div>
          <label class="block text-fuchsia-200 text-base font-medium mb-2"
            >Username</label
          >
          <input
            name="username"
            type="text"
            [(ngModel)]="username"
            class="w-full px-5 py-4 rounded-xl border border-gray-700 bg-gray-900 text-fuchsia-100 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-fuchsia-600 focus:border-transparent transition text-lg"
            placeholder="Enter Username"
          />
        </div>

        <div>
          <div class="flex justify-between items-center mb-2">
            <label class="block text-fuchsia-200 text-base font-medium"
              >Password</label
            >
            <a href="#" class="text-sm text-fuchsia-400 hover:text-fuchsia-300"
              >Forgot?</a
            >
          </div>
          <input
            name="password"
            type="password"
            [(ngModel)]="password"
            class="w-full px-5 py-4 rounded-xl border border-gray-700 bg-gray-900 text-fuchsia-100 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-fuchsia-600 focus:border-transparent transition text-lg"
            placeholder="••••••••"
          />
        </div>

        <button
          type="submit"
          [disabled]="loading || !loginForm.valid"
          class="w-full py-4 px-5 bg-gradient-to-r from-violet-900 violet-gray-700 to-fuchsia-800 hover:from-indigo-700 hover:to-purple-800 text-white font-semibold rounded-xl shadow-lg hover:shadow-fuchsia-900/40 transition duration-300 text-lg"
        >
          Sign In
        </button>
        <app-loader [isLoading]="loading"></app-loader>
      </form>

      <div class="mt-8 text-center">
        <p class="text-base text-fuchsia-200">
          Don't have an account?
          <a
            routerLink="/register"
            class="font-medium text-fuchsia-400 hover:text-fuchsia-200"
            >Sign up</a
          >
        </p>
      </div>
    </div>
  </div>
</div>

// client_react/src/Components/Login.jsx
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import useAuth from '../Hooks/useAuth';
import api from '../Hooks/interceptor';
import Loader from './Loader';

const Login = () => {
  const [username, setUsername] = useState('');
  const [password, setPassword] = useState('');
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const navigate = useNavigate();
  const { login, isLoggedIn } = useAuth();

  if (isLoggedIn) {
    navigate('/dashboard');
  }

  const handleLogin = async (e) => {
    e.preventDefault();
    if (!username || !password) return;

    setLoading(true);
    setError('');

    try {
      const response = await api.post('/api/login', {
        username,
        password
      });
      login(response.data.access_token, response.data.username);
      navigate('/dashboard');
    } catch (err) {
      setError('Login failed. Check your credentials.');
      console.error('Login error:', err);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-950 to-black flex items-center justify-center p-6">
      <div className="bg-gradient-to-br from-gray-900 via-gray-800 to-black rounded-3xl shadow-2xl overflow-hidden w-full max-w-xl border border-gray-800">
        <div className="text-center py-8 px-10">
          <h2 className="text-3xl font-bold text-white">Welcome Back</h2>
          <p className="text-indigo-200 text-lg mt-1">Sign in to your account</p>
        </div>

        <div className="border-t border-violet-700"></div>

        <div className="p-10">
          <form className="space-y-8" onSubmit={handleLogin}>
            <div>
              <label className="block text-fuchsia-200 text-base font-medium mb-2">
                Username
              </label>
              <input
                type="text"
                value={username}
                onChange={(e) => setUsername(e.target.value)}
                className="w-full px-5 py-4 rounded-xl border border-gray-700 bg-gray-900 text-fuchsia-100 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-fuchsia-600 focus:border-transparent transition text-lg"
                placeholder="Enter Username"
                required
              />
            </div>

            <div>
              <div className="flex justify-between items-center mb-2">
                <label className="block text-fuchsia-200 text-base font-medium">
                  Password
                </label>
              </div>
              <input
                type="password"
                value={password}
                onChange={(e) => setPassword(e.target.value)}
                className="w-full px-5 py-4 rounded-xl border border-gray-700 bg-gray-900 text-fuchsia-100 placeholder-gray-500 focus:outline-none focus:ring-2 focus:ring-fuchsia-600 focus:border-transparent transition text-lg"
                placeholder="••••••••"
                required
              />
            </div>

            <button
              type="submit"
              disabled={loading || !username || !password}
              className="w-full py-4 px-5 bg-gradient-to-r from-violet-900 via-gray-700 to-fuchsia-800 hover:from-indigo-700 hover:to-purple-800 text-white font-semibold rounded-xl shadow-lg hover:shadow-fuchsia-900/40 transition duration-300 text-lg disabled:opacity-50"
            >
              Sign In
            </button>
            
            {error && (
              <div className="mb-6 bg-red-900/30 border border-red-700 rounded-lg p-4">
                <p className="text-red-300">{error}</p>
              </div>
            )}
          </form>

          <div className="mt-8 text-center">
            <p className="text-base text-fuchsia-200">
              Don't have an account?
              <a
                href="/register"
                className="font-medium text-fuchsia-400 hover:text-fuchsia-200 ml-1"
              >
                Sign up
              </a>
            </p>
          </div>
        </div>
      </div>
      <Loader isLoading={loading} />
    </div>
  );
};

export default Login;
