// client_react/src/Components/Loader.jsx
const Loader = ({ isLoading }) => {
  if (!isLoading) return null;

  return (
    <div className="fixed inset-0 flex items-center justify-center z-50">
      <div className="animate-spin rounded-full text-violet-600 h-16 w-16 border-t-6 border-b-6 border-accent"></div>
    </div>
  );
};

export default Loader;

// client/src/app/components/loader/loader.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-loader',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './loader.component.html',
  styleUrls: ['./loader.component.css']
})
export class LoaderComponent {
  @Input() isLoading: boolean = false;
}
<div *ngIf="isLoading" class="fixed inset-0  flex items-center justify-center z-50">
  <div class="animate-spin rounded-full  text-violet-600 h-16 w-16 border-t-4 border-b-4 border-accent"></div>
</div>
